# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["usb_storage"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0d1439b2-2f08-403a-baf2-7b57513342a0";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "noatime"
      "subvol=root"
    ];
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/05aff299-343b-4cf7-ae20-78cff907ba23";

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/0d1439b2-2f08-403a-baf2-7b57513342a0";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "noatime"
      "subvol=nix"
    ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/0d1439b2-2f08-403a-baf2-7b57513342a0";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "noatime"
      "subvol=persist"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/84EA-15F6";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/684a1b30-1e9c-4aca-92eb-3c4d8148cd0b";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
