[backdrop]
enabled = true

[bar.default]
background_opacity = 0.89999997988343239
capsule = true
capsule_thickness = 0.73999998718500137
center = [ "workspaces" ]
contact_shadow = true
end = [
    "privacy",
    "tray",
    "volume",
    "brightness",
    "battery",
    "network",
    "bluetooth",
    "clipboard",
    "notifications",
    "control-center"
]
font_family = "Mononoki Nerd Font Mono"
font_weight = 400
margin_edge = 0
margin_ends = 0
padding = 6
radius = 0
radius_bottom_left = -6
radius_bottom_right = -6
radius_top_left = 0
radius_top_right = 0
shadow = false
start = [ "launcher", "clock", "group:g1", "active_window" ]

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "cpu", "ram" ]
    opacity = 1.0
    padding = 6.0

[calendar]
enabled = true

    [calendar.account.home_nextcloud]
    name = "Calendar"
    provider = "custom"
    server_url = "https://radicale.spoodythe.one/spoody/f6f1c1f0-8572-1aa7-e0fc-691ca214e37e/"
    type = "caldav"
    username = "spoody"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[hot_corners]
enabled = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 130.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 300.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 120.0

[location]
address = "Copenhagen"
auto_locate = true

[lockscreen]
allow_empty_password = true
fingerprint = false

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000002", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 64.0
    box_width = 416.0
    cx = 731.5
    cy = 601.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 32.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 176.0
    box_width = 272.0
    cx = 179.5
    cy = 113.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        background_opacity = 0.0
        background_padding = 16
        background_radius = 0
        center_text = false
        clock_style = "digital"
        font_family = "Mononoki Nerd Font Mono"
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 160.0
    box_width = 304.0
    cx = 1283.5
    cy = 121.0
    output = "eDP-1"
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        forecast_days = 1
        show_forecast = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 563.5
    cy = 399.0
    output = "eDP-1"
    rotation = 0.0
    type = "label"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        title = "Login"

[nightlight]
enabled = true

[notification]
layer = "overlay"

[osd]
background_opacity = 0.92999997921288013
position = "top_right"

[plugin_settings."noctalia/wallhaven"]
browser_open_near_click = true

[plugins]
enabled = []

[shell]
corner_radius_scale = 0.5000000074505806
date_format = "%A, %Y-%m-%d"
font_family = "Mononoki Nerd Font"
launch_apps_as_systemd_services = true
middle_click_opens_widget_settings = false
niri_overview_type_to_launch_enabled = false
offline_mode = false
password_style = "random"
polkit_agent = true

    [shell.animation]
    speed = 1.3500000201165676

    [shell.panel]
    borders = false
    clipboard_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    polkit_placement = "attached"
    transparency_mode = "soft"

    [shell.screen_corners]
    enabled = true
    size = 16

    [shell.screenshot]
    save_to_file = false

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    command = "systemctl suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[system.monitor]
cpu_poll_seconds = 10
memory_poll_seconds = 10
network_poll_seconds = 10

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "soft"

[theme.templates]
builtin_ids = [ "gtk4", "niri", "qt" ]
enable_community_templates = false

[wallpaper]
directory = "/home/nixos/.local/wallpapers"
directory_dark = "/home/nixos/.local/wallpapers"
directory_light = "/home/nixos/.local/wallpapers"
edge_smoothness = 0.0
transition = [ "disc", "stripes" ]
transition_on_startup = true

[widget.active_window]
title_scroll = "on_hover"

[widget.battery]
display_mode = "graphic"

[widget.cpu]
show_label = false

[widget.launcher]
glyph = "stack-2-filled"

[widget.network]
show_label = false

[widget.ram]
show_label = false

[widget.tray]
drawer = false
hidden = [ "blueman" ]

[widget.workspaces]
active_pill_size = 1.6500000000000001
display = "none"
